name: workflow

on:
    workflow_dispatch:
    
# permissions: 
#     actions: read
#     contents: read
#     artifact-metadata: read
#     repository-projects: read

env:
  CONNECTOR_URL: https://pipelineconnector-dev6.connectors.dev.signpath.io:15001
  ENDPOINT_KEY: GitHubCom 
  ORG_ID: 9ff791fc-c563-44e3-ab8c-86a33c910bbe
  INPUT_ARTIFACT: ./script.ps1
  OUTPUT_PATH: signed-artifact

jobs:
  build:
    runs-on: windows-latest
    environment: default
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Upload the artifcat file
        id: upload-artifact-step
        uses: actions/upload-artifact@v4
        with: 
          name: original-artifact
          path: ${{ env.INPUT_ARTIFACT }}
      - name: Run submit signing request
        id: submit_with_download
        uses: signpath/github-action-submit-signing-request@main
        with:
            connector-url: ${{ env.CONNECTOR_URL }}/GitHubActions/${{ env.ENDPOINT_KEY }}
            api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
            organization-id: ${{ env.ORG_ID }}
            project-slug: PipelineConnector
            # this SigningPolicy has auto-approve enabled, so you don't need to approve the signing request
            signing-policy-slug: test-signing
            artifact-configuration-slug: initial
            github-artifact-id: '${{ steps.upload-artifact-step.outputs.artifact-id }}'
            wait-for-completion: true
            output-artifact-directory: ${{ env.OUTPUT_PATH }}
      - name: Upload the signed artifact
        id: upload-signed-artifact-step
        uses: actions/upload-artifact@v4
        with: 
            name: signed-artifact
            path: ${{ env.OUTPUT_PATH }}
      - run: |
          echo "Signed Artifact Id: ${{ steps.upload-signed-artifact-step.outputs.artifact-id }}"
